@extends('user.layouts.app')
@section('title', 'Returns & Exchange')
@section('content')
  <div class="px-5 md:px-0 mx-auto max-w-7xl">
    <h1 class="font-bold text-2xl text-center my-5">RETURN & EXCHANGE POLICY</h1>
    <div class="space-y-8">
      {{-- Refund & Exchange Policy --}}
      <div class="space-y-2">
        <h5 class="font-medium">Refund & Exchange Policy</h5>
        <p class="text-sm text-gray-500 leading-6 text-justify">A refund or exchange may be requested at any time prior to your receipt of the merchandise. Your refund will include taxes paid and the cost of any additional protection or warranty programs purchased. After your receipt of merchandise, if you are dissatisfied for any reason, you may return it for a full refund, less delivery fees, so long as it is returned or exchanged within 7 days of pickup or delivery. To be eligible for return, except where prohibited by law, and unless your merchandise qualifies for replacement under a promotional program, Mattresses and Box Springs must have law tags attached, and be in sanitary condition, clean and free of tears, burns, stains of any kind. Except where prohibited by law, a 15% restocking fee may be charged on returned merchandise or cancelled orders. Refunds may only be made if merchandise is in " as-new" condition. " AS-IS" and " One Only" items are not refundable or exchangeable. Refunds will be in the same form as that of the original payment and issued only to the individual(s) listed in the invoice, except for cash. If your original payment was a cash payment and your refund exceeds $250, a refund check will be issued by our Corporate Office within 10 days and will be mailed to you by the store.</p>
      </div>
      {{-- 90-Day Price Lock --}}
      <div class="space-y-2">
        <h5 class="font-medium">90-Day Price Lock</h5>
        <p class="text-sm text-gray-500 leading-6 text-justify">Price Lock holds the price of merchandise for 90 days beginning on the date of your deposit. This policy does not guarantee availability of merchandise. Your purchase must be a minimum of $500 with a 10% down payment and payments of 10% of the original invoice total each month. You may cancel the price lock and receive a full refund if your request is made within 180 days of your last payment. After 180 days of inactivity, VALUE CITY FURNITURE/AMERICAN SIGNATURE FURNITURE will deduct a non-refundable of your last payment. After 180 days of inactivity, VALUE CITY FURNITURE/AMERICAN SIGNATURE FURNITURE/AMERICAN SIGNATURE FURNITURE will deduct a non-refundable $10 service fee from your invoice every month, except where prohibited by law.</p>
      </div>
      {{-- Guarantee Of Fabrics --}}
      <div class="space-y-2">
        <h5 class="font-medium">Guarantee Of Fabrics</h5>
        <p class="text-sm text-gray-500 leading-6 text-justify">A refund or exchange may be requested at any time prior to your receipt of the merchandise. Your refund will include taxes paid and the cost of any additional protection or warranty programs purchased. After your receipt of merchandise, if you are dissatisfied for any reason, you may return it for a full refund, less delivery fees, so long as it is returned or exchanged within 7 days of pickup or delivery. To be eligible for return, except where prohibited by law, and unless your merchandise qualifies for replacement under a promotional program, Mattresses and Box Springs must have law tags attached, and be in sanitary condition, clean and free of tears, burns, stains of any kind. Except where prohibited by law, a 15% restocking fee may be charged on returned merchandise or cancelled orders. Refunds may only be made if merchandise is in " as-new" condition. " AS-IS" and " One Only" items are not refundable or exchangeable. Refunds will be in the same form as that of the original payment and issued only to the individual(s) listed in the invoice, except for cash. If your original payment was a cash payment and your refund exceeds $250, a refund check will be issued by our Corporate Office within 10 days and will be mailed to you by the store.</p>
      </div>
      {{-- Merchandise Delivered By Store --}}
      <div class="space-y-2">
        <h5 class="font-medium">Merchandise Delivered By Store</h5>
        <p class="text-sm text-gray-500 leading-6 text-justify">A refund or exchange may be requested at any time prior to your receipt of the merchandise. Your refund will include taxes paid and the cost of any additional protection or warranty programs purchased. After your receipt of merchandise, if you are dissatisfied for any reason, you may return it for a full refund, less delivery fees, so long as it is returned or exchanged within 7 days of pickup or delivery. To be eligible for return, except where prohibited by law, and unless your merchandise qualifies for replacement under a promotional program, Mattresses and Box Springs must have law tags attached, and be in sanitary condition, clean and free of tears, burns, stains of any kind. Except where prohibited by law, a 15% restocking fee may be charged on returned merchandise or cancelled orders. Refunds may only be made if merchandise is in " as-new" condition. " AS-IS" and " One Only" items are not refundable or exchangeable. Refunds will be in the same form as that of the original payment and issued only to the individual(s) listed in the invoice, except for cash. If your original payment was a cash payment and your refund exceeds $250, a refund check will be issued by our Corporate Office within 10 days and will be mailed to you by the store.</p>
      </div>
      {{-- Merchandise Received By Manufacturer Parcel Shipping --}}
      <div class="space-y-2">
        <h5 class="font-medium">Merchandise Received By Manufacturer Parcel Shipping</h5>
        <p class="text-sm text-gray-500 leading-6 text-justify">A refund or exchange may be requested at any time prior to your receipt of the merchandise. Your refund will include taxes paid and the cost of any additional protection or warranty programs purchased. After your receipt of merchandise, if you are dissatisfied for any reason, you may return it for a full refund, less delivery fees, so long as it is returned or exchanged within 7 days of pickup or delivery. To be eligible for return, except where prohibited by law, and unless your merchandise qualifies for replacement under a promotional program, Mattresses and Box Springs must have law tags attached, and be in sanitary condition, clean and free of tears, burns, stains of any kind. Except where prohibited by law, a 15% restocking fee may be charged on returned merchandise or cancelled orders. Refunds may only be made if merchandise is in " as-new" condition. " AS-IS" and " One Only" items are not refundable or exchangeable. Refunds will be in the same form as that of the original payment and issued only to the individual(s) listed in the invoice, except for cash. If your original payment was a cash payment and your refund exceeds $250, a refund check will be issued by our Corporate Office within 10 days and will be mailed to you by the store.</p>
      </div>
      {{-- Merchandise Picked Up By Customer --}}
      <div class="space-y-2">
        <h5 class="font-medium">Merchandise Picked Up By Customer</h5>
        <p class="text-sm text-gray-500 leading-6 text-justify">A refund or exchange may be requested at any time prior to your receipt of the merchandise. Your refund will include taxes paid and the cost of any additional protection or warranty programs purchased. After your receipt of merchandise, if you are dissatisfied for any reason, you may return it for a full refund, less delivery fees, so long as it is returned or exchanged within 7 days of pickup or delivery. To be eligible for return, except where prohibited by law, and unless your merchandise qualifies for replacement under a promotional program, Mattresses and Box Springs must have law tags attached, and be in sanitary condition, clean and free of tears, burns, stains of any kind. Except where prohibited by law, a 15% restocking fee may be charged on returned merchandise or cancelled orders. Refunds may only be made if merchandise is in " as-new" condition. " AS-IS" and " One Only" items are not refundable or exchangeable. Refunds will be in the same form as that of the original payment and issued only to the individual(s) listed in the invoice, except for cash. If your original payment was a cash payment and your refund exceeds $250, a refund check will be issued by our Corporate Office within 10 days and will be mailed to you by the store.</p>
      </div>
      {{-- Warranty --}}
      <div class="space-y-2">
        <h5 class="font-medium">Warranty</h5>
        <p class="text-sm text-gray-500 leading-6 text-justify">Under conditions of normal usage VALUE CITY FURNITURE/AMERICAN SIGNATURE FURNITURE will conduct repairs on any defect in workmanship without any charge to the original purchaser for a one year period from the date of possession of the original purchase. VALUE CITY FURNITURE/AMERICAN SIGNATURE FURNITURE will not perform work or repair any furniture which may cause a hazard to our employees or our property. Warranty coverage does not apply to furniture that has been heavily soiled, stained, intentionally misused, altered, improperly cleaned, infested, damaged in transit, or otherwise damaged in a way that is not the result of defect in the workmanship of the product. If the item cannot be repaired to factory specifications, the item will be replaced with the same or comparable merchandise. If the same item is not available, VALUE CITY FURNITURE/AMERICAN SIGNATURE FURNITURE will issue an IN-STORE CREDIT towards new merchandise. Accessory items are warranted for a period of 90 days. " AS-IS" items carry no warranty and the sale is final (except where prohibited by law). For warranty claims on mattresses, box springs, or additional protection or warranty programs, refer to that warranty for service information.</p>
      </div>
    </div>
  </div>
@endsection
